require("conf.env")
require("conf.monitors")
require("conf.options")
require("conf.permissions")
require("conf.devices")
require("conf.gestures")
require("conf.animation")
require("conf.rules")
require("conf.gaming")
require("conf.binds")
require("conf.passthrough")
require("conf.autostart")

pcall(function()
	require("noctalia").apply_theme()
end)
