require("conf.env")
require("conf.monitors")
require("conf.options")
require("conf.animation")
require("conf.binds")
require("conf.autostart")

pcall(function()
	require("noctalia").apply_theme()
end)
