# GTK 4
# ---------------------------------------------

[Settings]
gtk-icon-theme-name=Tela-circle-black-dark
gtk-cursor-theme-name=capitaine-cursors
gtk-cursor-theme-size=24
# fcitx5 for gtk apps under xwayland; wayland gtk apps ignore this
gtk-im-module=fcitx
