#!/bin/sh

set_color_and_font() {
	color_font_file="$ROFI_HOME/theme/font-color.rasi"

	if [ ! -f "$ROFI_HOME/theme/colorscheme/$color.rasi" ]
	then
		color="catppuccin"
	fi

	echo "@import \"$ROFI_HOME/theme/colorscheme/$color.rasi\"" > "$color_font_file"
	echo "* { font: \"$font $font_size\"; }" >> "$color_font_file"
}

ROFI_HOME="$HOME/.config/rofi"
THEME="$ROFI_HOME/theme/dmenu.rasi"
WALLPAPER_DIR="$HOME/Resources/media/pictures/wallpaper/landscape/"

color="$1"
font="$2"
font_size="$3"

set_color_and_font

wall_dir="$(eza -1 "$WALLPAPER_DIR" | rofi -steal-focus -theme "$THEME" -p "tool:" -dmenu)"

[ -z "$wall_dir" ] && exit 0

find "$HOME"/Resources/media/pictures/wallpaper/landscape/"$wall_dir" -regextype awk -iregex ".*png|.*jpeg|.*jpg|.*gif|.*webp" -print0 | xargs -0 eza -1 --color=never --reverse --sort=created | nsxiv -i
