---
# Linux parallels vm
# ---------------------------------------------
#     ansible-playbook ansible/local.yml -e @ansible/hosts/mac-vm.yml

# Packages
# ---------------------------------------------
packages_exclude:
  - ollama
  - opencode


# Displays
# ---------------------------------------------
monitors:
  - output: Virtual-1
    mode: preferred
    position: auto
    scale: 1.6
