# Thinkpad T480
# ---------------------------------------------
#     ansible-playbook ansible/base.yml -e @ansible/hosts/t480.yml


# Noctalia
# ---------------------------------------------
wallpaper_directory: "~/assets/media/pics/wallpaper/landscape"


# Displays
# ---------------------------------------------
monitors:
  - output: eDP-1
    mode: preferred
    position: auto
    scale: 1.25

# Xft.dpi for xwayland apps: 96 * scale.
xwayland_dpi: 120

greeter_output:
  width: 1920
  height: 1080
  scale: 1.25
