---
# generic x86 qemu vm
# ---------------------------------------------
#     ansible-playbook ansible/base.yml -e @ansible/hosts/vm.yml


# Displays
# ---------------------------------------------
monitors:
  - output: eDP-1
    mode: preferred
    position: auto
    scale: 1.2

# Xft.dpi for xwayland apps: 96 * scale.
xwayland_dpi: 115

lockscreen_height: 900

greeter_output:
  width: 1920
  height: 1080
  scale: 1.2
