#!/usr/bin/env bash

readarray -t relative_path
length=${#relative_path[@]}
sww_options="
--transition-type wipe
--transition-fps 60
"

absolute_path=()
for file in "${relative_path[@]}"
do
	absolute_path+=("$(readlink -f "$file")")
done

case "$1" in
# Set as current wallpaper.
"w")
	swww img $sww_options "${relative_path[$(( "$length" - 1))]}"
	;;
# Set as favorite wallpaper.
"W")
	cp "${relative_path[$(( "$length" - 1))]}" ~/.config/hypr/subconfig/paths/favorite-wall
	;;
# Set as hyprlock wallpaper.
"e")
	cp "${relative_path[$(( "$length" - 1))]}" ~/.config/hypr/subconfig/paths/hyprlock-wall
	;;
"d")
	# Works when file contain space.
	for single in "${relative_path[@]}"
	do
		rm "$single"
	done
	;;
"c")
	wl-copy -n "${relative_path[@]}"
	;;
"C")
	wl-copy -n "${absolute_path[@]}"
	;;
"y")
	wl-copy < "${relative_path[$(( "$length" - 1))]}"
	;;

# for debugging purposes
"r")
	echo "${absolute_path[@]}" ;;
esac
