require("plugins")
require("pluginConfig.catppuccin")
require("pluginConfig.lsp")
require("pluginConfig.nvimtree")
require("pluginConfig.lualine")
require("pluginConfig.cmp")
require("pluginConfig.null-ls")
require("pluginConfig.comment")

require("core.colorscheme")
require("core.options")
require("core.autocmd")
require("core.keybindings")
