# GTK 3
# ---------------------------------------------

[Settings]
gtk-theme-name=adw-gtk3-dark
gtk-application-prefer-dark-theme=1
gtk-icon-theme-name=Tela-circle-black-dark
gtk-cursor-theme-name=capitaine-cursors
gtk-cursor-theme-size=24
