require("catppuccin").setup({
	-- use command :CatppuccinCompile to compile this config into cache
	compile_path = vim.fn.stdpath("cache") .. "/catppuccin",
	flavour = "macchiato",
	transparent_background = true,
	term_colors = true,
	dim_inactive = {
		enabled = false,
		shade = "dark",
		percentage = 0.15,
	},
	styles = {
		comments = { "italic" },
		conditionals = { "italic" },
		conditionals = {},
		loops = {},
		functions = {},
		keywords = {},
		strings = {},
		variables = {},
		numbers = {},
		booleans = {},
		properties = {},
		types = {},
		operators = {},
	},
	integrations = {
		cmp = true,
		gitsigns = true,
		nvimtree = true,
		telescope = true,
		treesitter = true,
	},
	color_overrides = {},
	custom_highlights = {},
})
