#
# System wide zsh environment variables
#

# ------------------------------------ XDG stuff ---------------------------------------
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_STATE_HOME="$HOME"/.local/state
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_CACHE_HOME="$HOME"/.cache
# export XDG_CONFIG_DIRS="$XDG_CONFIG_HOME":/etc/xdg
# export XDG_DATA_DIRS="$XDG_DATA_HOME":/usr/local/share:/usr/share


# ------------------------------- XDG user directories --------------------------------
export XDG_DESKTOP_DIR="$HOME/Desktop"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_MUSIC_DIR="$HOME/Music"
export XDG_PICTURES_DIR="$HOME/Pictures"
export XDG_PUBLICSHARE_DIR="$HOME/Public"
export XDG_TEMPLATES_DIR="$HOME/Templates"
export XDG_VIDEOS_DIR="$HOME/Videos"
[ -r "$XDG_CONFIG_HOME/user-dirs.dirs" ] && . "$XDG_CONFIG_HOME/user-dirs.dirs"


export ZDOTDIR="$XDG_CONFIG_HOME"/shell/zsh
