#
# System wide zsh environment variables
#

# ------------------------------------ XDG stuff ---------------------------------------
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_STATE_HOME="$HOME"/.local/state
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_CACHE_HOME="$HOME"/.cache
# export XDG_CONFIG_DIRS="$XDG_CONFIG_HOME":/etc/xdg
# export XDG_DATA_DIRS="$XDG_DATA_HOME":/usr/local/share:/usr/share


export ZDOTDIR="$XDG_CONFIG_HOME"/shell/zsh
