# Outfit
# ---------------------------------------------
background_opacity 0.92
dynamic_background_opacity yes
window_padding_width 5 15

# catppuccin color scheme: https://github.com/catppuccin/kitty
# include themes/solarized-light.conf
include themes/gruvbox/gruvboxdark.conf
# include themes/papercolor/light.conf
# ---------------------------------------------

tab_bar_edge top

# Font setting
# ---------------------------------------------
font_family      Osaka
# font_family      JetBrainsMono Nerd Font
# font_family      CodeNewRoman Nerd Font Mono
# font_family      JetBrainsMono Nerd Font Mono
font_size 18.0

# Nerd Fonts v3.3.0

symbol_map U+e000-U+e00a,U+ea60-U+ebeb,U+e0a0-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b7,U+e700-U+e8ef,U+ed00-U+efc1,U+f000-U+f2ff,U+f000-U+f2e0,U+f300-U+f381,U+f400-U+f533,U+f0001-U+f1af0,U+25ef JetBrainsMono Nerd Font Mono
symbol_map U+4e00-U+9fff PingFang TC Regular
# ---------------------------------------------


# Cursor setting
# ---------------------------------------------
shell_integration no-cursor
cursor_shape block
cursor_blink_interval 0
# ---------------------------------------------

scrollback_lines 5000
enable_audio_bell no
# cursor_underline_thickness 2.0

paste_actions no-op

# Key bind
macos_option_as_alt yes

map ctrl+shift+u no_op
map alt+cmd+k no_op
map alt+cmd+h no_op

map cmd+enter new_os_window
map cmd+n next_tab
map cmd+p prev_tab
map cmd+, no_op

map cmd+t new_tab
map cmd+w close_tab
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7

map cmd+h prev_tab
# map cmd+j send_text all \x1b2
# map cmd+k send_text all \x1b3
map cmd+l next_tab

map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+shift+equal change_font_size all 0

map ctrl+shift+up set_background_opacity -0.1
map ctrl+shift+down set_background_opacity +0.1
map ctrl+shift+right set_background_opacity default

map shift+enter send_text all \x1b[13;2u

hide_window_decorations yes

clipboard_control write-primary write-clipboard no-append
allow_remote_control yes

# scrollback_pager nvim -c 'setlocal nonumber nolist showtabline=0 foldcolumn=0|Man!' -c "autocmd VimEnter * normal G" -
# scrollback_pager nvim --noplugin -u ~/.config/kitty/scrollback-pager/nvim/init.vim -c "silent write! /tmp/kitty_scrollback_buffer | te cat /tmp/kitty_scrollback_buffer - " -c "silent $"
