# Outfit
# ---------------------------------------------
background_opacity 0.92
dynamic_background_opacity yes
window_padding_width 5 15

# catppuccin color scheme: https://github.com/catppuccin/kitty
# include themes/solarized-light.conf
include themes/gruvbox/gruvboxdark.conf
# ---------------------------------------------

tab_bar_edge top

# Font setting
# ---------------------------------------------
# font_family      JetBrains Mono
font_family      JetBrainsMono Nerd Font
# font_family      CodeNewRoman Nerd Font Mono
# font_family      JetBrainsMono Nerd Font Mono
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
font_size 17.0

symbol_map  U+E000-U+E00D JetBrainsMono Nerd Font Mono
symbol_map U+e0a0-U+e0a2,U+e0b0-U+e0b3 JetBrainsMono Nerd Font Mono
symbol_map U+e0a3-U+e0a3,U+e0b4-U+e0c8,U+e0cc-U+e0d2,U+e0d4-U+e0d4 JetBrainsMono Nerd Font Mono
symbol_map U+e5fa-U+e62b JetBrainsMono Nerd Font Mono
symbol_map U+e700-U+e7c5 JetBrainsMono Nerd Font Mono
symbol_map U+f000-U+f2e0 JetBrainsMono Nerd Font Mono
symbol_map U+e200-U+e2a9 JetBrainsMono Nerd Font Mono
symbol_map U+f400-U+f4a8,U+2665-U+2665,U+26A1-U+26A1,U+f27c-U+f27c JetBrainsMono Nerd Font Mono
symbol_map U+F300-U+F313 JetBrainsMono Nerd Font Mono
symbol_map U+23fb-U+23fe,U+2b58-U+2b58 JetBrainsMono Nerd Font Mono
symbol_map U+f500-U+fd46 JetBrainsMono Nerd Font Mono
symbol_map U+e300-U+e3eb JetBrainsMono Nerd Font Mono
symbol_map U+21B5,U+25B8,U+2605,U+2630,U+2632,U+E0A3,U+E615,U+E62B JetBrainsMono Nerd Font Mono
symbol_map U+ea61,U+f01a7,U+ea93 JetBrainsMono Nerd Font Mono
symbol_map U+ea61,U+f01a7 JetBrainsMono Nerd Font Mono
symbol_map U+f165d,U+f165c,U+1f855 JetBrainsMono Nerd Font
symbol_map U+f0219,U+f00e4 JetBrainsMono Nerd Font Mono
# ---------------------------------------------


# Cursor setting
# ---------------------------------------------
shell_integration no-cursor
cursor_shape block
cursor_blink_interval 0
# ---------------------------------------------

scrollback_lines 5000
enable_audio_bell no
# cursor_underline_thickness 2.0

# Key bind
macos_option_as_alt yes
map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+shift+equal change_font_size all 0

map ctrl+shift+j set_background_opacity -0.1
map ctrl+shift+k set_background_opacity +0.1
map ctrl+shift+h set_background_opacity default

map cmd+enter no_op
map cmd+n next_tab
map cmd+p previous_tab
map cmd+t new_tab
map cmd+w close_tab
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
# map alt+enter no_op

# scrollback_pager nvim -c 'setlocal nonumber nolist showtabline=0 foldcolumn=0|Man!' -c "autocmd VimEnter * normal G" - 
# scrollback_pager nvim --noplugin -u ~/.config/kitty/scrollback-pager/nvim/init.vim -c "silent write! /tmp/kitty_scrollback_buffer | te cat /tmp/kitty_scrollback_buffer - " -c "silent $"
