#!/bin/sh

# cliphist: https://github.com/sentriz/cliphist

set_color_and_font() {
	color_font_file="$ROFI_HOME/theme/font-color.rasi"

	if [ ! -f "$ROFI_HOME/theme/colorscheme/$color.rasi" ]
	then
		color="catppuccin"
	fi

	echo "@import \"$ROFI_HOME/theme/colorscheme/$color.rasi\"" > "$color_font_file"
	echo "* { font: \"$font $font_size\"; }" >> "$color_font_file"
}

ROFI_HOME="$HOME/.config/rofi"
THEME="$ROFI_HOME/theme/dmenu.rasi"

color="$1"
font="$2"
font_size="$3"

set_color_and_font

option="$(printf "select an item from clipboard\ndelete an item from clipboard\nwipe out the clipboard database\n" | rofi -steal-focus -theme "$THEME" -p "option:" -dmenu)"

if [ -z "$option" ]; then
	dunstify -I ~/.config/dunst/images/icons/screenshot.svg "cancelled"
	exit 0
fi

case "$option" in
	"select an item from clipboard")
    cliphist list | rofi -steal-focus -theme "$THEME" -dmenu | cliphist decode | wl-copy
		;;
	"delete an item from clipboard")
    cliphist list | rofi -steal-focus -theme "$THEME" -dmenu | cliphist delete
		;;
	"wipe out the clipboard database")
		cliphist wipe
		;;
esac
