# ----------------------------------------------------------------------------
# Desktop environment.
# ----------------------------------------------------------------------------
{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

let
  dotfiles = ../../config;
  cfg = config.desktop;
  username = config.core.username;

  # Seed for the screenshot-dir state file (home.activation)
  screenshotDirState = pkgs.writeText "screenshot-dir" (cfg.screenshotDirectory + "\n");

  # stable is still 4.7 with the old INI config.
  pkgs-unstable = import inputs.nixpkgs-unstable { inherit (pkgs) system; };

  # conf/monitors.lua
  monitorsLua =
    "-- Generated by nix (modules/desktop.nix). Rebuilds replace it.\n\n"
    + "return {\n"
    + lib.concatMapStrings (
      m:
      "\t{ output = ${builtins.toJSON m.output}, mode = ${builtins.toJSON m.mode}, "
      + "position = ${builtins.toJSON m.position}, scale = ${builtins.toJSON m.scale} },\n"
    ) cfg.monitors
    + "}\n";

  xresources = ''
    ! Rendered by nix (modules/desktop.nix). Rebuilds replace it.

    Xft.dpi: ${toString cfg.xwaylandDpi}
    Xft.antialias: true
    Xft.hinting: true
    Xft.rgba: rgb
    Xft.autohint: true
    Xft.hintstyle: hintfull
    Xft.lcdfilter: lcddefault

    Xcursor.theme: capitaine-cursors
    Xcursor.size: 24
  '';
in
{
  # upstream nixos module: wires greetd to the greeter and manages the
  # declarative /var/lib/noctalia-greeter/greeter.toml from `settings`
  imports = [ inputs.noctalia-greeter.nixosModules.default ];

  # per-host knobs
  # ---------------------------------------------
  options.desktop = {
    monitors = lib.mkOption {
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            output = lib.mkOption {
              type = lib.types.str;
              default = "";
              description = "Output name (see hyprctl monitors); empty matches every output.";
            };
            mode = lib.mkOption {
              type = lib.types.str;
              default = "preferred";
              description = "Resolution and refresh rate, e.g. 2560x1600@60.";
            };
            position = lib.mkOption {
              type = lib.types.str;
              default = "auto";
              description = "Placement in the layout, e.g. 0x0.";
            };
            scale = lib.mkOption {
              type = lib.types.number;
              default = 1;
              description = "Output scale factor.";
            };
          };
        }
      );
      default = [ ];
      description = "Display rules for this host, written to the hypr state file.";
    };

    wallpaperDirectory = lib.mkOption {
      type = lib.types.str;
      default = "~/assets/media/pics/wallpaper/landscape";
      description = "Directory noctalia picks wallpapers from.";
    };

    screenshotDirectory = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = "Noctalia screenshot directory; empty means XDG Pictures.";
    };

    xwaylandDpi = lib.mkOption {
      type = lib.types.nullOr lib.types.int;
      default = null;
      description = "Xft.dpi for xwayland apps, typically 96 * scale.";
    };
  };

  config = {
    # hyprland
    # ---------------------------------------------
    programs.hyprland.enable = true;
    programs.hyprland.withUWSM = true;
    xdg.portal.extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
    programs.dconf.enable = true;

    # nixpkgs keeps schemas in a layout the plain gsettings CLI never
    # searches; without this every `gsettings set` fails
    environment.sessionVariables.XDG_DATA_DIRS = [
      "${pkgs.gsettings-desktop-schemas}/share/gsettings-schemas/${pkgs.gsettings-desktop-schemas.name}"
    ];

    # qt reads the qt5ct/qt6ct color schemes the noctalia template writes
    qt = {
      enable = true;
      platformTheme = "qt5ct";
    };

    # display manager
    # ---------------------------------------------
    programs.noctalia-greeter = {
      enable = true;
      settings = {
        appearance.hide_logo = true;
        cursor = {
          theme = "capitaine-cursors";
          size = 24;
          path = "${pkgs.capitaine-cursors}/share/icons";
        };
      };
    };

    security.polkit.extraConfig = ''
      polkit.addRule(function(action, subject) {
          if ((action.id == "org.noctalia.greeter.sync-appearance" ||
               action.id == "org.noctalia.greeter.apply-appearance") &&
              subject.active && subject.local) {
              return polkit.Result.YES;
          }
      });
    '';

    # networking
    # ---------------------------------------------
    networking.networkmanager.enable = true;
    networking.networkmanager.connectionConfig."ipv4.dhcp-client-id" = "mac";

    hardware.bluetooth.enable = true;
    services.upower.enable = true;
    services.power-profiles-daemon.enable = true;
    services.fprintd.enable = true;
    services.accounts-daemon.enable = true;

    # noctalia battery-threshold plugin
    users.groups.battery_ctl = { };
    users.users.${username}.extraGroups = [ "battery_ctl" ];
    services.udev.extraRules = ''
      SUBSYSTEM=="power_supply", KERNEL=="BAT*", \
          RUN+="${pkgs.coreutils}/bin/chgrp battery_ctl /sys$devpath/charge_control_end_threshold", \
          RUN+="${pkgs.coreutils}/bin/chmod g+w /sys$devpath/charge_control_end_threshold"
    '';

    # audio
    # ---------------------------------------------
    security.rtkit.enable = true;
    services.pipewire = {
      enable = true;
      alsa.enable = true;
      pulse.enable = true;
    };

    # packages
    # ---------------------------------------------
    environment.systemPackages = with pkgs; [
      # desktop shell
      inputs.noctalia.packages.${stdenv.hostPlatform.system}.default
      libnotify

      # terminal & viewers
      kitty
      zathura
      cava
      pkgs-unstable.swayimg

      # themes
      adw-gtk3
      capitaine-cursors
      (tela-circle-icon-theme.override { colorVariants = [ "black" ]; })
      glib
      gsettings-desktop-schemas

      # screen pickers & clipboard (binds.lua)
      grim
      slurp
      hyprpicker
      wl-clipboard
      (tesseract.override { enableLanguages = [ "eng" ]; })

      # xwayland dpi (autostart.lua xrdb-merges the state xresources)
      xorg.xrdb
      xauth
    ];

    fonts.packages = with pkgs; [
      inter
      libertinus
      noto-fonts-cjk-sans
      noto-fonts-cjk-serif
      nerd-fonts.code-new-roman
      nerd-fonts.jetbrains-mono
      udev-gothic-nf
      (callPackage ../packages/apple-color-emoji.nix { })
      (callPackage ../packages/apple-fonts.nix { })
    ];

    fonts.fontconfig.defaultFonts = {
      serif = [
        "Libertinus Serif"
        "Noto Serif CJK SC"
      ];
      sansSerif = [
        "SF Pro Text"
        "Inter"
        "Noto Sans CJK SC"
      ];
      monospace = [
        "JetBrainsMono Nerd Font"
        "Noto Sans Mono CJK SC"
      ];
      emoji = [ "Apple Color Emoji" ];
    };

    fonts.fontconfig.localConf = ''
      <?xml version="1.0"?>
      <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
      <fontconfig>
        <match target="pattern">
          <test name="family"><string>SF Pro Display Clock</string></test>
          <edit name="family" mode="assign" binding="strong"><string>SF Pro Display</string></edit>
          <edit name="weight" mode="assign" binding="strong"><const>semibold</const></edit>
        </match>
      </fontconfig>
    '';


    # home-manager
    # ---------------------------------------------
    home-manager.users.${username} =
      { lib, ... }:
      {
      xdg.configFile =
        let
          desktopDirs = [
            "gtk-3.0"
            "gtk-4.0"
            "hypr"
            "kitty"
            "noctalia"
            "swayimg"
            "zathura"
          ];
        in
        lib.genAttrs desktopDirs (dir: {
          source = dotfiles + "/config/${dir}";
          recursive = true;
        })
        // {
          # per-host values, merged over config.toml (zz- sorts last)
          "noctalia/zz-host.toml".text = ''
            # Host overlay, rendered by nix (modules/desktop.nix).

            [wallpaper]
            directory = "${cfg.wallpaperDirectory}"

            [shell.screenshot]
            directory = "${cfg.screenshotDirectory}"
          '';
        };

      # swayimg is the default image viewer (arch sets this via mimeapps.list;
      # here home-manager owns ~/.config/mimeapps.list)
      xdg.mimeApps = {
        enable = true;
        defaultApplications = lib.genAttrs [
          "image/png"
          "image/jpeg"
          "image/gif"
          "image/webp"
          "image/bmp"
          "image/tiff"
          "image/avif"
        ] (_: "swayimg.desktop");
      };

      # local plugins load from XDG data
      xdg.dataFile."noctalia/plugins" = {
        source = dotfiles + "/share/noctalia/plugins";
        recursive = true;
      };

      xdg.dataFile."nerd-glyphs" = {
        source = dotfiles + "/share/nerd-glyphs";
        recursive = true;
      };

      # per-host display rules for conf/monitors.lua, xresources for xwayland
      xdg.stateFile =
        lib.optionalAttrs (cfg.monitors != [ ]) {
          "hypr/monitors.lua".text = monitorsLua;
        }
        // lib.optionalAttrs (cfg.xwaylandDpi != null) {
          "hypr/xresources".text = xresources;
        };

      # Seeded from screenshotDirectory but a plain writable file, created once
      home.activation.screenshotDir = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        f="''${XDG_STATE_HOME:-$HOME/.local/state}/hypr/screenshot-dir"
        [ -e "$f" ] || run install -Dm644 ${screenshotDirState} "$f"
      '';

      home.extraActivationPath = [ pkgs.gawk ];
      home.activation.noctaliaPruneState = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        run sh ${../../lib/deploy/noctalia-prune-state}
      '';
    };
  };
}
