# ----------------------------------------------------------------------------
# Desktop environment.
# ----------------------------------------------------------------------------
{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

let
  dotfiles = ../../config;
  cfg = config.desktop;
  username = config.core.username;

  # conf/monitors.lua
  monitorsLua =
    "-- Generated by nix (modules/desktop.nix). Rebuilds replace it.\n\n"
    + "return {\n"
    + lib.concatMapStrings (
      m:
      "\t{ output = ${builtins.toJSON m.output}, mode = ${builtins.toJSON m.mode}, "
      + "position = ${builtins.toJSON m.position}, scale = ${builtins.toJSON m.scale} },\n"
    ) cfg.monitors
    + "}\n";

  xresources = ''
    ! Rendered by nix (modules/desktop.nix). Rebuilds replace it.

    Xft.dpi: ${toString cfg.xwaylandDpi}
    Xft.antialias: true
    Xft.hinting: true
    Xft.rgba: rgb
    Xft.autohint: true
    Xft.hintstyle: hintfull
    Xft.lcdfilter: lcddefault

    Xcursor.theme: capitaine-cursors
    Xcursor.size: 24
  '';
in
{
  # per-host knobs
  # ---------------------------------------------
  options.desktop = {
    monitors = lib.mkOption {
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            output = lib.mkOption {
              type = lib.types.str;
              default = "";
              description = "Output name (see hyprctl monitors); empty matches every output.";
            };
            mode = lib.mkOption {
              type = lib.types.str;
              default = "preferred";
              description = "Resolution and refresh rate, e.g. 2560x1600@60.";
            };
            position = lib.mkOption {
              type = lib.types.str;
              default = "auto";
              description = "Placement in the layout, e.g. 0x0.";
            };
            scale = lib.mkOption {
              type = lib.types.number;
              default = 1;
              description = "Output scale factor.";
            };
          };
        }
      );
      default = [ ];
      description = "Display rules for this host, written to the hypr state file.";
    };

    wallpaperDirectory = lib.mkOption {
      type = lib.types.str;
      default = "~/Resources/media/pictures/wallpaper/landscape";
      description = "Directory noctalia picks wallpapers from.";
    };

    screenshotDirectory = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = "Noctalia screenshot directory; empty means XDG Pictures.";
    };

    xwaylandDpi = lib.mkOption {
      type = lib.types.nullOr lib.types.int;
      default = null;
      description = "Xft.dpi for xwayland apps, typically 96 * scale.";
    };
  };

  config = {
    # hyprland
    # ---------------------------------------------
    programs.hyprland.enable = true;
    xdg.portal.extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
    programs.dconf.enable = true;

    # nixpkgs keeps schemas in a layout the plain gsettings CLI never
    # searches; without this every `gsettings set` fails
    environment.sessionVariables.XDG_DATA_DIRS = [
      "${pkgs.gsettings-desktop-schemas}/share/gsettings-schemas/${pkgs.gsettings-desktop-schemas.name}"
    ];

    # qt reads the qt5ct/qt6ct color schemes the noctalia template writes
    qt = {
      enable = true;
      platformTheme = "qt5ct";
    };

    # audio
    # ---------------------------------------------
    security.rtkit.enable = true;
    services.pipewire = {
      enable = true;
      alsa.enable = true;
      pulse.enable = true;
    };

    # packages
    # ---------------------------------------------
    environment.systemPackages = with pkgs; [
      # desktop shell
      inputs.noctalia.packages.${stdenv.hostPlatform.system}.default
      libnotify

      # terminal & viewers
      kitty
      zathura
      cava

      # themes
      adw-gtk3
      capitaine-cursors
      (tela-circle-icon-theme.override { colorVariants = [ "black" ]; })
      glib
      gsettings-desktop-schemas

      # screen pickers & clipboard (binds.lua)
      grim
      slurp
      hyprpicker
      wl-clipboard
      (tesseract.override { enableLanguages = [ "eng" ]; })

      # xwayland dpi (autostart.lua xrdb-merges the state xresources)
      xorg.xrdb
    ];

    fonts.packages = with pkgs; [
      inter
      libertinus
      noto-fonts-cjk-sans
      noto-fonts-cjk-serif
      nerd-fonts.code-new-roman
      nerd-fonts.jetbrains-mono
      udev-gothic-nf
      (callPackage ../packages/apple-color-emoji.nix { })
    ];

    fonts.fontconfig.defaultFonts = {
      serif = [
        "Libertinus Serif"
        "Noto Serif CJK SC"
      ];
      sansSerif = [
        "Inter"
        "Noto Sans CJK SC"
      ];
      monospace = [
        "JetBrainsMono Nerd Font"
        "Noto Sans Mono CJK SC"
      ];
      emoji = [ "Apple Color Emoji" ];
    };


    # home-manager
    # ---------------------------------------------
    home-manager.users.${username} = {
      xdg.configFile =
        let
          desktopDirs = [
            "gtk-3.0"
            "gtk-4.0"
            "hypr"
            "kitty"
            "noctalia"
            "zathura"
          ];
        in
        lib.genAttrs desktopDirs (dir: {
          source = dotfiles + "/config/${dir}";
          recursive = true;
        })
        // {
          # per-host values, merged over config.toml (zz- sorts last)
          "noctalia/zz-host.toml".text = ''
            # Host overlay, rendered by nix (modules/desktop.nix).

            [wallpaper]
            directory = "${cfg.wallpaperDirectory}"

            [shell.screenshot]
            directory = "${cfg.screenshotDirectory}"
          '';
        };

      # local plugins load from XDG data
      xdg.dataFile."noctalia/plugins" = {
        source = dotfiles + "/share/noctalia/plugins";
        recursive = true;
      };

      # per-host display rules for conf/monitors.lua, xresources for xwayland
      xdg.stateFile =
        lib.optionalAttrs (cfg.monitors != [ ]) {
          "hypr/monitors.lua".text = monitorsLua;
        }
        // lib.optionalAttrs (cfg.xwaylandDpi != null) {
          "hypr/xresources".text = xresources;
        };
    };
  };
}
