# ----------------------------------------------------------------------------
# Desktop environment.
# ----------------------------------------------------------------------------
{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

let
  dotfiles = ../../config;
  cfg = config.desktop;
  username = config.core.username;

  # Seed for the screenshot-dir state file (home.activation)
  screenshotDirState = pkgs.writeText "screenshot-dir" (cfg.screenshotDirectory + "\n");

  # stable is still 4.7 with the old INI config.
  pkgs-unstable = import inputs.nixpkgs-unstable { inherit (pkgs) system; };

  # conf/monitors.lua
  monitorsLua =
    "-- Generated by nix (modules/desktop.nix). Rebuilds replace it.\n\n"
    + "return {\n"
    + lib.concatMapStrings (
      m:
      "\t{ output = ${builtins.toJSON m.output}, mode = ${builtins.toJSON m.mode}, "
      + "position = ${builtins.toJSON m.position}, scale = ${builtins.toJSON m.scale} },\n"
    ) cfg.monitors
    + "}\n";

  # conf/devices.lua
  devicesLua =
    "-- Generated by nix (modules/desktop.nix). Rebuilds replace it.\n\n"
    + "return ${lib.generators.toLua { } cfg.inputDevices}\n";

  # Lock screen login box, one per declared monitor (noctalia/zz-host.toml).
  loginBoxToml = lib.concatMapStrings (
    m:
    let
      id = builtins.toJSON "lockscreen-login-box@${m.output}";
    in
    ''

      [lockscreen_widgets.widget.${id}]
      box_height = 70.0
      box_width = 240.0
      cx = 800.0
      cy = 913.0
      enabled = true
      output = ${builtins.toJSON m.output}
      placement_height = 1000.0
      placement_width = 1600.0
      rotation = 0.0
      type = "login_box"

          [lockscreen_widgets.widget.${id}.settings]
          background_color = "surface_variant"
          background_opacity = 0.0
          background_radius = 12.0
          center_password_text = false
          input_opacity = 0.59999999999999998
          input_radius = 6.0
          layout = "compact"
          show_caps_lock = true
          show_keyboard_layout = true
          show_login_button = false
          show_media = true
          show_session_buttons = true
          show_unlock_hint = false
          show_weather = true
    ''
  ) (lib.filter (m: m.output != "") cfg.monitors);

  lockClockToml =
    let
      named = map (m: m.output) (lib.filter (m: m.output != "") cfg.monitors);
      outputs = if named == [ ] then [ "" ] else named;
      height = frac: fallback: if cfg.lockscreenHeight != null then cfg.lockscreenHeight * frac else fallback;
      pair =
        out:
        let
          sfx = lib.optionalString (out != "") "@${out}";
          clock = builtins.toJSON "lockscreen-clock${sfx}";
          date = builtins.toJSON "lockscreen-date${sfx}";
        in
        ''

          [lockscreen_widgets.widget.${clock}]
          box_height = ${builtins.toJSON (height 0.161 161.0)}
          box_width = 560.0
          cx = 800.0
          cy = 196.0
          enabled = true
          output = ${builtins.toJSON out}
          placement_height = 1000.0
          placement_width = 1600.0
          rotation = 0.0
          type = "clock"

              [lockscreen_widgets.widget.${clock}.settings]
              background = false
              center_text = true
              clock_style = "digital"
              color = "#cfcfcfe6"
              font_family = "SF Pro Display Clock"
              shadow = false

          [lockscreen_widgets.widget.${date}]
          box_height = ${builtins.toJSON (height 0.038 38.0)}
          box_width = 480.0
          cx = 800.0
          cy = 112.0
          enabled = true
          output = ${builtins.toJSON out}
          placement_height = 1000.0
          placement_width = 1600.0
          rotation = 0.0
          type = "clock"

              [lockscreen_widgets.widget.${date}.settings]
              background = false
              center_text = true
              color = "#bdbdbdd9"
              font_family = "SF Pro Display Clock"
              format = "{:%A, %B %-d}"
              shadow = false
        '';
    in
    lib.concatMapStrings pair outputs;

  # media widget width (unset keeps the value in config.toml)
  mediaToml = lib.optionalString (cfg.mediaMaxLength != null) ''

    [widget.media]
    max_length = ${toString cfg.mediaMaxLength}
  '';

  xresources = ''
    ! Rendered by nix (modules/desktop.nix). Rebuilds replace it.

    Xft.dpi: ${toString cfg.xwaylandDpi}
    Xft.antialias: true
    Xft.hinting: true
    Xft.rgba: rgb
    Xft.autohint: true
    Xft.hintstyle: hintfull
    Xft.lcdfilter: lcddefault

    Xcursor.theme: capitaine-cursors
    Xcursor.size: 24
  '';
in
{
  # upstream nixos module: wires greetd to the greeter and manages the
  # declarative /var/lib/noctalia-greeter/greeter.toml from `settings`
  imports = [ inputs.noctalia-greeter.nixosModules.default ];

  # per-host knobs
  # ---------------------------------------------
  options.desktop = {
    monitors = lib.mkOption {
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            output = lib.mkOption {
              type = lib.types.str;
              default = "";
              description = "Output name (see hyprctl monitors); empty matches every output.";
            };
            mode = lib.mkOption {
              type = lib.types.str;
              default = "preferred";
              description = "Resolution and refresh rate, e.g. 2560x1600@60.";
            };
            position = lib.mkOption {
              type = lib.types.str;
              default = "auto";
              description = "Placement in the layout, e.g. 0x0.";
            };
            scale = lib.mkOption {
              type = lib.types.number;
              default = 1;
              description = "Output scale factor.";
            };
          };
        }
      );
      default = [ ];
      description = "Display rules for this host, written to the hypr state file.";
    };

    inputDevices = lib.mkOption {
      type = lib.types.attrsOf (lib.types.attrsOf lib.types.anything);
      default = { };
      example = {
        "tpps/2-ibm-trackpoint".sensitivity = -0.4;
        "logitech-g-pro--1".accel_profile = "flat";
      };
      description = ''
        hl.device options per input device, keyed by the device name from
        `hyprctl devices`, on top of the global input options.
      '';
    };

    wallpaperDirectory = lib.mkOption {
      type = lib.types.str;
      default = "~/assets/media/pics/wallpaper/landscape";
      description = "Directory noctalia picks wallpapers from.";
    };

    screenshotDirectory = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = "Noctalia screenshot directory; empty means XDG Pictures.";
    };

    recordingDirectory = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = "Screen recording directory; empty means the recorder plugin's ~/Videos/Recordings.";
    };

    xwaylandDpi = lib.mkOption {
      type = lib.types.nullOr lib.types.int;
      default = null;
      description = "Xft.dpi for xwayland apps, typically 96 * scale.";
    };

    lockscreenHeight = lib.mkOption {
      type = lib.types.nullOr lib.types.int;
      default = null;
      description = "Logical height of the lock screen's output (mode height / scale); scales the lock clock.";
    };

    mediaMaxLength = lib.mkOption {
      type = lib.types.nullOr lib.types.int;
      default = null;
      description = "Width cap of the bar's media widget, in noctalia units (times the bar scale); depends on the screen's logical width.";
    };
  };

  config = {
    # hyprland
    # ---------------------------------------------
    programs.hyprland.enable = true;
    programs.hyprland.withUWSM = true;
    xdg.portal.extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
    programs.dconf.enable = true;

    # nixpkgs keeps schemas in a layout the plain gsettings CLI never
    # searches; without this every `gsettings set` fails
    environment.sessionVariables.XDG_DATA_DIRS = [
      "${pkgs.gsettings-desktop-schemas}/share/gsettings-schemas/${pkgs.gsettings-desktop-schemas.name}"
    ];

    # screen recording
    # ---------------------------------------------
    programs.gpu-screen-recorder.enable = true;

    # noctalia pass needs a graphical pinentry
    programs.gnupg.agent.pinentryPackage = pkgs.pinentry-gnome3;

    # qt reads the qt5ct/qt6ct color schemes the noctalia template writes
    qt = {
      enable = true;
      platformTheme = "qt5ct";
    };

    # display manager
    # ---------------------------------------------
    programs.noctalia-greeter = {
      enable = true;
      settings = {
        appearance.hide_logo = true;
        cursor = {
          theme = "capitaine-cursors";
          size = 24;
          path = "${pkgs.capitaine-cursors}/share/icons";
        };
      };
    };

    security.polkit.extraConfig = ''
      polkit.addRule(function(action, subject) {
          if ((action.id == "org.noctalia.greeter.sync-appearance" ||
               action.id == "org.noctalia.greeter.apply-appearance") &&
              subject.active && subject.local) {
              return polkit.Result.YES;
          }
      });
    '';

    # networking
    # ---------------------------------------------
    networking.networkmanager.enable = true;
    networking.networkmanager.connectionConfig."ipv4.dhcp-client-id" = "mac";

    hardware.bluetooth.enable = true;
    services.upower.enable = true;
    services.power-profiles-daemon.enable = true;
    services.fprintd.enable = true;
    services.accounts-daemon.enable = true;

    # noctalia battery-threshold plugin
    users.groups.battery_ctl = { };
    users.users.${username}.extraGroups = [ "battery_ctl" ];
    services.udev.extraRules = ''
      SUBSYSTEM=="power_supply", KERNEL=="BAT*", \
          RUN+="${pkgs.coreutils}/bin/chgrp battery_ctl /sys$devpath/charge_control_end_threshold", \
          RUN+="${pkgs.coreutils}/bin/chmod g+w /sys$devpath/charge_control_end_threshold"
    '';

    # audio
    # ---------------------------------------------
    security.rtkit.enable = true;
    services.pipewire = {
      enable = true;
      alsa.enable = true;
      pulse.enable = true;
      jack.enable = true;
    };

    # packages
    # ---------------------------------------------
    environment.systemPackages = with pkgs; [
      # desktop shell
      inputs.noctalia.packages.${stdenv.hostPlatform.system}.default
      libnotify

      # terminal & viewers
      kitty
      zathura
      cava
      pkgs-unstable.swayimg
      mpv

      chromium
      transmission_4-gtk

      # themes
      adw-gtk3
      capitaine-cursors
      (tela-circle-icon-theme.override { colorVariants = [ "black" ]; })
      glib
      gsettings-desktop-schemas

      # screen pickers & clipboard (binds.lua)
      grim
      slurp
      still
      hyprpicker

      # wl-copy guesses the mime type with xdg-mime, and nixpkgs' xdg-mime
      # prefers perl's slow `mimetype`. Leave it out so xdg-mime uses `file`.
      ((wl-clipboard.override {
        xdg-utils = xdg-utils.override {
          perlPackages = perlPackages // { FileMimeInfo = emptyDirectory; };
        };
      }).overrideAttrs (old: {
        postInstall = lib.replaceStrings [ "--suffix" ] [ "--prefix" ] old.postInstall;
      }))
      wev
      (tesseract.override { enableLanguages = [ "eng" ]; })

      # xwayland dpi (autostart.lua xrdb-merges the state xresources)
      xorg.xrdb
      xauth
    ];

    fonts.packages = with pkgs; [
      inter
      libertinus
      noto-fonts-cjk-sans
      noto-fonts-cjk-serif
      nerd-fonts.code-new-roman
      nerd-fonts.jetbrains-mono
      udev-gothic-nf
      (callPackage ../packages/apple-color-emoji.nix { })
      (callPackage ../packages/apple-fonts.nix { })
    ];

    nixpkgs.config.allowUnfreePackages = [
      "apple-color-emoji"
      "apple-fonts-sf-pro"
    ];

    fonts.fontconfig.defaultFonts = {
      serif = [
        "Libertinus Serif"
        "Noto Serif CJK SC"
      ];
      sansSerif = [
        "SF Pro Text"
        "Inter"
        "Noto Sans CJK SC"
      ];
      monospace = [
        "JetBrainsMono Nerd Font"
        "Noto Sans Mono CJK SC"
      ];
      emoji = [ "Apple Color Emoji" ];
    };

    fonts.fontconfig.localConf = ''
      <?xml version="1.0"?>
      <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
      <fontconfig>
        <match target="pattern">
          <test name="family"><string>SF Pro Display Clock</string></test>
          <edit name="family" mode="assign" binding="strong"><string>SF Pro Display</string></edit>
          <edit name="weight" mode="assign" binding="strong"><const>semibold</const></edit>
        </match>
      </fontconfig>
    '';


    # home-manager
    # ---------------------------------------------
    home-manager.users.${username} =
      { lib, ... }:
      {
      xdg.configFile =
        let
          desktopDirs = [
            "gtk-3.0"
            "gtk-4.0"
            "hypr"
            "kitty"
            "noctalia"
            "swayimg"
            "zathura"
          ];
        in
        lib.genAttrs desktopDirs (dir: {
          source = dotfiles + "/config/${dir}";
          recursive = true;
        })
        // {
          # per-host values, merged over config.toml (zz- sorts last)
          "noctalia/zz-host.toml".text = ''
            # Host overlay, rendered by nix (modules/desktop.nix).

            [wallpaper]
            directory = "${cfg.wallpaperDirectory}"

            [shell.screenshot]
            directory = "${cfg.screenshotDirectory}"

            [plugin_settings."noctalia/screen_recorder"]
            directory = "${cfg.recordingDirectory}"
          '' + loginBoxToml + lockClockToml + mediaToml;
        };

      # swayimg is the default image viewer (arch sets this via mimeapps.list;
      # here home-manager owns ~/.config/mimeapps.list)
      xdg.mimeApps = {
        enable = true;
        defaultApplications = lib.genAttrs [
          "image/png"
          "image/jpeg"
          "image/gif"
          "image/webp"
          "image/bmp"
          "image/tiff"
          "image/avif"
        ] (_: "swayimg.desktop");
      };

      # local plugins load from XDG data
      xdg.dataFile."noctalia/plugins" = {
        source = dotfiles + "/share/noctalia/plugins";
        recursive = true;
      };

      xdg.dataFile."nerd-glyphs" = {
        source = dotfiles + "/share/nerd-glyphs";
        recursive = true;
      };

      # gtk key theme with just Ctrl+E and Ctrl+W (autostart.lua selects it)
      xdg.dataFile."themes/emacs-lite" = {
        source = dotfiles + "/share/themes/emacs-lite";
        recursive = true;
      };

      # per-host display rules for conf/monitors.lua, input device options for
      # conf/devices.lua, xresources for xwayland
      xdg.stateFile =
        {
          "hypr/devices.lua".text = devicesLua;
        }
        // lib.optionalAttrs (cfg.monitors != [ ]) {
          "hypr/monitors.lua".text = monitorsLua;
        }
        // lib.optionalAttrs (cfg.xwaylandDpi != null) {
          "hypr/xresources".text = xresources;
        };

      # Seeded from screenshotDirectory but a plain writable file, created once
      home.activation.screenshotDir = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        f="''${XDG_STATE_HOME:-$HOME/.local/state}/hypr/screenshot-dir"
        [ -e "$f" ] || run install -Dm644 ${screenshotDirState} "$f"
      '';

      home.extraActivationPath = [ pkgs.gawk ];
      home.activation.noctaliaPruneState = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        run sh ${../../lib/deploy/noctalia-prune-state}
      '';
    };
  };
}
