# Terminal
# ---------------------------------------------
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-kitty:Tc"

# extended keys, so kitty can send shift+enter etc.
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

set -g focus-events on
set -g set-clipboard on
set -g allow-passthrough on            # terminal file manager preview
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
# ---------------------------------------------


# General
# ---------------------------------------------
set -s escape-time 1                   # avoid ESC delay
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on                        # mouse works as expected
set -g mode-keys vi
set -g history-limit 10000

setw -g monitor-activity on
set -g visual-activity off
# ---------------------------------------------


# Colorscheme
# ---------------------------------------------
source ~/.config/tmux/themes/gruvbox/base16-gruvbox-dark-hard.conf
# ---------------------------------------------


# Prefix
# ---------------------------------------------
unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind b set-option -g status
bind r source-file ~/.config/tmux/tmux.conf
# ---------------------------------------------


# Copy mode
# ---------------------------------------------
bind Escape copy-mode
unbind p
bind p paste-buffer
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
# to the previous and next prompt.
bind-key -T copy-mode-vi '.' send -X search-forward "󱙝 "
bind-key -T copy-mode-vi ',' send -X search-backward "󱙝 "
# ---------------------------------------------


# Panes and windows
# ---------------------------------------------
# split and open in the same directory (it will follow link).
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# moving between window.
bind N prev

# resize panes
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# @pane-is-vim is set by smart-splits.nvim.
bind-key -n C-h if -F "#{@pane-is-vim}" 'send-keys C-h' 'select-pane -L'
bind-key -n C-j if -F "#{@pane-is-vim}" 'send-keys C-j' 'select-pane -D'
bind-key -n C-k if -F "#{@pane-is-vim}" 'send-keys C-k' 'select-pane -U'
bind-key -n C-l if -F "#{@pane-is-vim}" 'send-keys C-l' 'select-pane -R'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# Send commands to all panels.
# bind y setw synchronize-panes on \; display-message "Sync ON"
# bind Y setw synchronize-panes off \; display-message "Sync OFF"
# ---------------------------------------------


# Popups
# ---------------------------------------------
bind-key g display-popup -d '#{pane_current_path}' -w 80% -h 80% -E "lazygit"
bind-key s display-popup -d '#{pane_current_path}' -w 60% -h 60% -E "$SHELL"
bind-key S display-popup -d '$HOME/Documents/learning/notes' -w 60% -h 60% -E "cd ~/Documents/learning/notes && nvim quick-note.md"
# ---------------------------------------------
