# Linux
# ---------------------------------------------
map alt+enter new_os_window
map alt+t new_tab
map alt+w close_tab

map alt+shift+h prev_tab
map alt+shift+l next_tab

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7

# Rename the focused tab.
map alt+shift+r set_tab_title
map ctrl+alt+shift+r set_tab_title ""
# ---------------------------------------------
